const rooms = [
  {
    image: 'https://commonsinn.ca/wp-content/uploads/2023/04/IMG_6717-jpg.webp',
    name: 'Deluxe Room',
    beds: 2,
    id: 1,
    size: '35 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar'],
    price: 120,
    description: 'A spacious deluxe room with modern amenities and a beautiful view. This room is perfect for couples or small families, offering comfort and luxury. Enjoy complimentary Wi-Fi, a minibar stocked with your favorite drinks, and a flat-screen TV for your entertainment.',
    availability: true,
    rating: 4.5,
  },
  {
    image: 'https://lh3.googleusercontent.com/Z0pyfQ_25E8V1tPKwwwKBn06KZZxje8pwYq_ZeR9k1ItHKDPXxRE0nw9yXE3EkWDfZFzsQDIXgTuWrjzEH4HmHoUVVpHq4oScvQPqkOpSEILskLUbXg=w396-rw',
    name: 'Deluxe Room',
    beds: 3,
    id: 2,
    size: '40 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar', 'Balcony'],
    price: 150,
    description: 'A luxurious deluxe room with extra space and a private balcony. Ideal for families or groups, this room offers an exceptional stay experience with beautiful views from the balcony. Enjoy the modern decor and all the amenities needed for a comfortable stay, including air conditioning, Wi-Fi, and a minibar.',
    availability: false,
    rating: 4.7,
  },
  {
    image: 'https://www.chelseatoronto.com/en/uploads/images/2023/03/chelsea-hotel-executive-room2.jpg',
    name: 'Executive Room',
    beds: 2,
    id: 3,
    size: '45 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar', 'Work Desk'],
    price: 200,
    description: 'An executive room designed for business travelers, featuring a spacious work desk and ergonomic chair. This room provides a quiet and productive environment, along with luxurious touches like a fully stocked minibar and high-speed Wi-Fi. Ideal for guests who need to balance work and relaxation during their stay.',
    availability: true,
    rating: 4.8,
  },
  {
    image: 'https://www.lottehotel.com/content/dam/lotte-hotel/lotte/yangon/accommodation/hotel/suite/royalsuite/180712-49-2000-acc-yangon-hotel.jpg.thumb.768.768.jpg',
    name: 'Suite',
    beds: 4,
    id: 4,
    size: '60 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar', 'Living Area', 'Kitchenette'],
    price: 300,
    description: 'A spacious suite perfect for extended stays or larger families. This suite includes a separate living area and a kitchenette, providing all the comforts of home. Enjoy the luxury of space and privacy, along with premium amenities such as a flat-screen TV, air conditioning, and a fully stocked minibar.',
    availability: true,
    rating: 4.9,
  },
  {
    image: 'https://st.hzcdn.com/simgs/pictures/family-rooms/colorful-great-room-laura-lee-home-img~ca910f5b0e986f7f_14-8913-1-e244175.jpg',
    name: 'Family Room',
    beds: 5,
    id: 5,
    size: '55 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar', 'Kids Play Area'],
    price: 250,
    description: 'A family room designed to accommodate larger families, featuring a kids play area and ample sleeping arrangements. This room ensures a fun and comfortable stay for families, with plenty of space for everyone to relax. Enjoy modern amenities including Wi-Fi, air conditioning, and a flat-screen TV.',
    availability: false,
    rating: 4.6,
  },
  {
    image: 'https://amorgoshotel.com/wp-content/uploads/2014/12/Amorgos-Standard-Room2-e1464286437370.jpg',
    name: 'Standard Room',
    beds: 1,
    id: 6,
    size: '25 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV'],
    price: 100,
    description: 'A cozy standard room perfect for solo travelers or couples. This room offers all the essentials for a comfortable stay, including high-speed Wi-Fi, air conditioning, and a flat-screen TV. Enjoy a relaxing and affordable stay with all the necessary amenities.',
    availability: true,
    rating: 4.2,
  },
  {
    image: 'https://www.parkregisgoa.in/wp-content/uploads/2020/12/room-premium-room-1-2520x1400.jpg',
    name: 'Premium Room',
    beds: 2,
    id: 7,
    size: '50 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV', 'Minibar', 'Jacuzzi'],
    price: 220,
    description: 'A premium room offering the ultimate in luxury and comfort. This room features a private Jacuzzi, perfect for relaxing after a long day. Enjoy premium amenities such as a fully stocked minibar, high-speed Wi-Fi, and a flat-screen TV. Ideal for guests seeking a luxurious and indulgent stay.',
    availability: true,
    rating: 4.9,
  },
  {
    image: 'https://www.queensangeles.com/media/k2/galleries/219/eco_05.jpg',
    name: 'Economy Room',
    beds: 1,
    id: 8,
    size: '20 sqm',
    amenities: ['Wi-Fi', 'Air Conditioning', 'TV'],
    price: 80,
    description: 'An economy room that offers great value for money. This room is perfect for budget-conscious travelers, providing all the essential amenities for a comfortable stay. Enjoy free Wi-Fi, air conditioning, and a flat-screen TV in a compact yet cozy space.',
    availability: true,
    rating: 4.0,
  },
];

export {
  rooms,
};
